# Generated by Django 4.2.3 on 2023-07-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_movie_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="special",
            field=models.BooleanField(default=False),
        ),
    ]
